idf_component_register(
    SRCS
        "app_main.c"
        "screen/screen.c"
        "hw/hw.c"
        "hw/imu.c"
        "hw/sdcard.c"
        "net/net.c"
        "stock/stock.c"
        "appman/appman.c"
        "apps/app_market.c"
        "apps/app_stock.c"
        "apps/app_font_cn_16.c"
    INCLUDE_DIRS
        "."
        "appman"
        "apps"
        "hw"
        "net"
        "screen"
        "stock"
    REQUIRES
        esp_lcd
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        esp_http_client
        driver
        esp_adc
        esp_timer
        json
        esp_lvgl_port
        lvgl
        fatfs
        sdmmc
        vfs
    PRIV_REQUIRES
        mbedtls
)
